services:
  # A web service to run the Telegram bot
  - type: web
    name: tg-news-feed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m tg_news_feed.main
    repo: https://github.com/gtmengine/tgchannels.git  # Updated repository URL
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 7735328862:AAFrcBtnZEmL9O-kM0dZ2Y_yDoFh11ICm40
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: FEEDBACK_FORM
        sync: false
      - key: PARSER_INTERVAL_MINUTES
        value: 5
      - key: DB_PATH
        value: /var/data/db.sqlite
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1 